services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: weatherforecastDb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: weatherforecast-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: WeatherForecast.Api/Dockerfile
    container_name: weatherforecast-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=weatherforecastDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sqlserver
      - redis
    restart: on-failure

volumes:
  sqlvolume:
